const fs = require('fs');
const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🔐 BOT TOKEN SETUP HELPER');
console.log('==========================\n');

// Check current .env
const envFile = '.env';
let currentEnv = {};
if (fs.existsSync(envFile)) {
    console.log('Current .env file found.');
    const content = fs.readFileSync(envFile, 'utf8');
    content.split('\n').forEach(line => {
        if (line.includes('=') && !line.startsWith('#')) {
            const [key, value] = line.split('=');
            currentEnv[key.trim()] = value.trim();
        }
    });
}

const tokens = {
    'OUT_BOT_TOKEN': 'Token for Out Bot (from @BotFather)',
    'APP_BOT_TOKEN': 'Main bot token',
    'TELEGRAM_BOT_TOKEN': 'General Telegram bot token',
    'DATABASE_URL': 'Database connection URL (optional)'
};

const newEnv = { ...currentEnv };

function askQuestion(question, defaultValue = '') {
    return new Promise((resolve) => {
        readline.question(question, (answer) => {
            resolve(answer || defaultValue);
        });
    });
}

async function setup() {
    console.log('\nCurrent tokens (masked):');
    Object.entries(currentEnv).forEach(([key, value]) => {
        if (key.includes('TOKEN') || key.includes('KEY')) {
            const masked = value.length > 8 ? 
                value.substring(0, 4) + '****' + value.substring(value.length - 4) : 
                '****';
            console.log(`  ${key}: ${masked}`);
        }
    });

    console.log('\nSetup new tokens (press Enter to skip):');
    
    for (const [key, description] of Object.entries(tokens)) {
        const current = currentEnv[key] || '';
        const answer = await askQuestion(
            `${description}\n${key} [${current ? 'current set' : 'not set'}]: `
        );
        
        if (answer) {
            newEnv[key] = answer;
        } else if (current) {
            newEnv[key] = current;
        }
    }

    // Write new .env file
    let envContent = '# Bot Tokens Configuration\n';
    envContent += '# Generated by setup script\n\n';
    
    Object.entries(newEnv).forEach(([key, value]) => {
        envContent += `${key}=${value}\n`;
    });

    console.log('\n📝 Writing new .env file...');
    fs.writeFileSync(envFile, envContent);
    console.log('✅ .env file updated!');
    
    // Show summary
    console.log('\n📋 SUMMARY:');
    console.log('File saved: .env');
    console.log('Tokens configured:');
    Object.keys(newEnv).forEach(key => {
        if (key.includes('TOKEN') || key.includes('KEY')) {
            console.log(`  ✓ ${key}`);
        }
    });

    console.log('\n🚀 Next steps:');
    console.log('1. Install dependencies: npm install');
    console.log('2. Start bots: node start_bots_safe.js');
    console.log('3. Test Out Bot: node bots/out_bot/index.js');
    
    readline.close();
}

setup().catch(console.error);
